<template>
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column">
          <h1 class="title">Vue Project Template</h1>
          <h2 class="subtitle">Generated by <a href="https://github.com/vuejs/vue-cli" target="_blank">vue-cli</a></h2>
        </div>

        <div class="column is-narrow">
          <a href="https://bulma.io">
            <img src="https://bulma.io/images/made-with-bulma--white.png" alt="Made with Bulma" width="256" height="48">
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
</template>

<script>
export default {
  name: 'Hero',
};
</script>

<style lang="scss" scoped>
</style>
